import Head from "next/head";
import Navbar from "../components/Navbar";

// Components
export default function Home() {
  return (
    <div>
      <Head>
        <title>
          BB Agency - Human Experience Design and Development Agency
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Div */}
      <div className="relative bg-custom-background-green px-5">
        <div className="max-w-screen-xl mx-auto">
          <Navbar />
        </div>
      </div>
    </div>
  );
}
